// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebWallet.Models;

#nullable disable

namespace WebWallet.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20211202192253_Data2")]
    partial class Data2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("WebWallet.Models.WalletModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassPhrase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserFName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserLName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WalletName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
